### PR TITLE
Use Parcel to bundle source files and NPM Scripts

### LINKED ISSUE #9: use npm scripts instead of gulp

### PR DESCRIPTION
**Pull request by VitorLuizC**
I've removed Webpack & Gulp and just use Parcel + NPM Scripts instead.

Closes #9

### CODE REVIEW

**Comment by krtr** [comment]
Hey, nice to see external contributions here :1st_place_medal: 

I have:
1. switched to your fork
2. `$ yarn`
2. `$ npm run build`
3. `$ npm run run`
4. navigated http://localhost:2137/

here is what I'm getting:
error
network

Looks like SpriteGL is wrapped in parcel module and `SpriteGL` object is not exposed as global value, (TibiaJS needs it as such, topic for another discussion)

Can you give me some info how to change that parcel behavior? (I'm using parcel for first time)

**Comment by VitorLuizC** [comment]
Really sorry, I'll fix this ASAP. Seems like parcel mess SpriteGL scope and can't define it's variables as global ones

**Comment by VitorLuizC** [comment]
I'll wait until you review https://github.com/krtr/SpriteGL/pull/4 to change this PR

😃

**Comment by krtr** [comment]
@VitorLuizC sorry for delay, your other PR have just been merged

**Comment by VitorLuizC** [comment]
No problem, @krtr. I just installed SpriteGL and fixed a small error with the types of the configuration

**Comment by krtr** [comment]
@VitorLuizC works great!

**Pull request merged**
